//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://equifax.com/WebService", ConfigurationName="ServiceReference1.WSIdValidatorEndpoint")]
    public interface WSIdValidatorEndpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.validacionPreguntasResponse> validacionPreguntasAsync(ServiceReference1.validacionPreguntas request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.cambioClaveResponse> cambioClaveAsync(ServiceReference1.cambioClave request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.listadoPreguntasResponse> listadoPreguntasAsync(ServiceReference1.listadoPreguntas request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equifax.com/WebService/types")]
    public partial class EstructuraValidacionPreguntas
    {
        
        private DatoPregunta[] datoPreguntaField;
        
        private Header headerField;
        
        private string numeroOperacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datoPregunta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public DatoPregunta[] datoPregunta
        {
            get
            {
                return this.datoPreguntaField;
            }
            set
            {
                this.datoPreguntaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Header header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string numeroOperacion
        {
            get
            {
                return this.numeroOperacionField;
            }
            set
            {
                this.numeroOperacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equifax.com/WebService/types")]
    public partial class DatoPregunta
    {
        
        private string categoriaPreguntaField;
        
        private string numeroOpcionField;
        
        private string numeroPreguntaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string categoriaPregunta
        {
            get
            {
                return this.categoriaPreguntaField;
            }
            set
            {
                this.categoriaPreguntaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string numeroOpcion
        {
            get
            {
                return this.numeroOpcionField;
            }
            set
            {
                this.numeroOpcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string numeroPregunta
        {
            get
            {
                return this.numeroPreguntaField;
            }
            set
            {
                this.numeroPreguntaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equifax.com/WebService/types")]
    public partial class Candidato
    {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string codigoInternoField;
        
        private string codigoInterno1Field;
        
        private string codigoInterno2Field;
        
        private string inicioValidacionField;
        
        private string nombresField;
        
        private string numeroDocumentoField;
        
        private System.Nullable<int> tipoDocumentoField;
        
        private string digitoVerificadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codigoInterno
        {
            get
            {
                return this.codigoInternoField;
            }
            set
            {
                this.codigoInternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string codigoInterno1
        {
            get
            {
                return this.codigoInterno1Field;
            }
            set
            {
                this.codigoInterno1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string codigoInterno2
        {
            get
            {
                return this.codigoInterno2Field;
            }
            set
            {
                this.codigoInterno2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string inicioValidacion
        {
            get
            {
                return this.inicioValidacionField;
            }
            set
            {
                this.inicioValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string digitoVerificador
        {
            get
            {
                return this.digitoVerificadorField;
            }
            set
            {
                this.digitoVerificadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equifax.com/WebService/types")]
    public partial class EstructuraListadoPreguntas
    {
        
        private Candidato candidatoField;
        
        private Header headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Candidato candidato
        {
            get
            {
                return this.candidatoField;
            }
            set
            {
                this.candidatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Header header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equifax.com/WebService/types")]
    public partial class Header
    {
        
        private string canalField;
        
        private string claveField;
        
        private string modeloField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string canal
        {
            get
            {
                return this.canalField;
            }
            set
            {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string modelo
        {
            get
            {
                return this.modeloField;
            }
            set
            {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equifax.com/WebService/types")]
    public partial class EstructuraUsuario
    {
        
        private string canalField;
        
        private string claveActualField;
        
        private string claveNuevaField;
        
        private string claveNuevaConfirmarField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string canal
        {
            get
            {
                return this.canalField;
            }
            set
            {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string claveActual
        {
            get
            {
                return this.claveActualField;
            }
            set
            {
                this.claveActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string claveNueva
        {
            get
            {
                return this.claveNuevaField;
            }
            set
            {
                this.claveNuevaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string claveNuevaConfirmar
        {
            get
            {
                return this.claveNuevaConfirmarField;
            }
            set
            {
                this.claveNuevaConfirmarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionPreguntas", WrapperNamespace="http://equifax.com/WebService/types", IsWrapped=true)]
    public partial class validacionPreguntas
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://equifax.com/WebService/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiceReference1.EstructuraValidacionPreguntas EstructuraValidacionPreguntas_1;
        
        public validacionPreguntas()
        {
        }
        
        public validacionPreguntas(ServiceReference1.EstructuraValidacionPreguntas EstructuraValidacionPreguntas_1)
        {
            this.EstructuraValidacionPreguntas_1 = EstructuraValidacionPreguntas_1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionPreguntasResponse", WrapperNamespace="http://equifax.com/WebService/types", IsWrapped=true)]
    public partial class validacionPreguntasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://equifax.com/WebService/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string result;
        
        public validacionPreguntasResponse()
        {
        }
        
        public validacionPreguntasResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambioClave", WrapperNamespace="http://equifax.com/WebService/types", IsWrapped=true)]
    public partial class cambioClave
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://equifax.com/WebService/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiceReference1.EstructuraUsuario EstructuraUsuario_1;
        
        public cambioClave()
        {
        }
        
        public cambioClave(ServiceReference1.EstructuraUsuario EstructuraUsuario_1)
        {
            this.EstructuraUsuario_1 = EstructuraUsuario_1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cambioClaveResponse", WrapperNamespace="http://equifax.com/WebService/types", IsWrapped=true)]
    public partial class cambioClaveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://equifax.com/WebService/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string result;
        
        public cambioClaveResponse()
        {
        }
        
        public cambioClaveResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listadoPreguntas", WrapperNamespace="http://equifax.com/WebService/types", IsWrapped=true)]
    public partial class listadoPreguntas
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://equifax.com/WebService/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ServiceReference1.EstructuraListadoPreguntas EstructuraListadoPreguntas_1;
        
        public listadoPreguntas()
        {
        }
        
        public listadoPreguntas(ServiceReference1.EstructuraListadoPreguntas EstructuraListadoPreguntas_1)
        {
            this.EstructuraListadoPreguntas_1 = EstructuraListadoPreguntas_1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listadoPreguntasResponse", WrapperNamespace="http://equifax.com/WebService/types", IsWrapped=true)]
    public partial class listadoPreguntasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://equifax.com/WebService/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string result;
        
        public listadoPreguntasResponse()
        {
        }
        
        public listadoPreguntasResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WSIdValidatorEndpointChannel : ServiceReference1.WSIdValidatorEndpoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WSIdValidatorEndpointClient : System.ServiceModel.ClientBase<ServiceReference1.WSIdValidatorEndpoint>, ServiceReference1.WSIdValidatorEndpoint
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSIdValidatorEndpointClient() : 
                base(WSIdValidatorEndpointClient.GetDefaultBinding(), WSIdValidatorEndpointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSIdValidatorEndpointImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSIdValidatorEndpointClient(EndpointConfiguration endpointConfiguration) : 
                base(WSIdValidatorEndpointClient.GetBindingForEndpoint(endpointConfiguration), WSIdValidatorEndpointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSIdValidatorEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSIdValidatorEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSIdValidatorEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSIdValidatorEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSIdValidatorEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.validacionPreguntasResponse> ServiceReference1.WSIdValidatorEndpoint.validacionPreguntasAsync(ServiceReference1.validacionPreguntas request)
        {
            return base.Channel.validacionPreguntasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.validacionPreguntasResponse> validacionPreguntasAsync(ServiceReference1.EstructuraValidacionPreguntas EstructuraValidacionPreguntas_1)
        {
            ServiceReference1.validacionPreguntas inValue = new ServiceReference1.validacionPreguntas();
            inValue.EstructuraValidacionPreguntas_1 = EstructuraValidacionPreguntas_1;
            return ((ServiceReference1.WSIdValidatorEndpoint)(this)).validacionPreguntasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.cambioClaveResponse> ServiceReference1.WSIdValidatorEndpoint.cambioClaveAsync(ServiceReference1.cambioClave request)
        {
            return base.Channel.cambioClaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.cambioClaveResponse> cambioClaveAsync(ServiceReference1.EstructuraUsuario EstructuraUsuario_1)
        {
            ServiceReference1.cambioClave inValue = new ServiceReference1.cambioClave();
            inValue.EstructuraUsuario_1 = EstructuraUsuario_1;
            return ((ServiceReference1.WSIdValidatorEndpoint)(this)).cambioClaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.listadoPreguntasResponse> ServiceReference1.WSIdValidatorEndpoint.listadoPreguntasAsync(ServiceReference1.listadoPreguntas request)
        {
            return base.Channel.listadoPreguntasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.listadoPreguntasResponse> listadoPreguntasAsync(ServiceReference1.EstructuraListadoPreguntas EstructuraListadoPreguntas_1)
        {
            ServiceReference1.listadoPreguntas inValue = new ServiceReference1.listadoPreguntas();
            inValue.EstructuraListadoPreguntas_1 = EstructuraListadoPreguntas_1;
            return ((ServiceReference1.WSIdValidatorEndpoint)(this)).listadoPreguntasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSIdValidatorEndpointImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSIdValidatorEndpointImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://accepwse.equifax.com.pe/WSIdValidatornew/WSIdValidatorEndpoint");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSIdValidatorEndpointClient.GetBindingForEndpoint(EndpointConfiguration.WSIdValidatorEndpointImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSIdValidatorEndpointClient.GetEndpointAddress(EndpointConfiguration.WSIdValidatorEndpointImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WSIdValidatorEndpointImplPort,
        }
    }
}
